spring:
    application:
        name: email
    mail:
        host: smtp.gmail.com
        password: ${GOOGLE_SMTP_APP_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: rehabit.munka@gmail.com

email-config:
    from: "rehabit.munka@gmail.com"
    to: "rehabit.munka@gmail.com"
    subject: "árvíztűrő tükörfúrógép - ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP"
